### ISSUE TITLE
[Request] Provide already compiled binaries

### ISSUE THREAD

**Issue by di57inct** [In-line/FakeServerQueries#1]
Hello, thanks for updating this useful module. Can you please provide links to already compiled binaries for at least Windows if you can't for Linux too? Thanks in advance.

**Comment by di57inct** [comment]
PS: I can provide access to a Linux virtual machine if you want to compile it for linux too. Thanks again.

**Comment by In-line** [comment]
Releases are here: https://github.com/In-line/FakeServerQueries/releases
I'm too lazy to compile for windows (I need to setup VM for it with mingw)
